os:
  - linux
  
sudo: required

language: node_js

notifications:
  slack: lincedintallerii:0mRgaQ0KRHMiKHjlCed7FZ1W

node_js:
  - "node"

services:
  - docker

branches:
  only:
  - master
  - dev

before_install:
  - docker-compose build
  - docker-compose up -d
  - docker ps

before_script:
  - sudo apt-get install -y python python-pycurl python-pip
  - sudo pip install pyresttest
  
script:
  - resttest.py http://localhost:8080 src/test/jobsPositionsTest.yaml
  - resttest.py http://localhost:8080 src/test/categoriesTest.yaml
  - resttest.py http://localhost:8080 src/test/skillsTest.yaml

after_script:
  - docker-compose stop db lincedin
